# Site settings
author: Max Zimmerman
title: Module 1 Project
header-img: img/home-bg.png
email: mzimmer52@gmail.com
copyright_name: Max Zimmerman
description: > # this means to ignore newlines until "baseurl:"
  Best Practices for Web Scraping with Beautiful Soup
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mzimmer52

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
